walletProvider:
  PROCIVIS_ONE:
    params:
      public:
        walletName: "Procivis One Dev Wallet"
        walletInstanceAttestation:
          integrityCheck:
            android:
              bundleId: ch.procivis.one.wallet.dev
              signingCertificateFingerprints: [
                  "FA:C6:17:45:DC:09:03:78:6F:B9:ED:E6:2A:96:2B:39:9F:73:48:F0:BB:6F:89:9B:83:32:66:75:91:03:3B:9C", # local
                  "3C:54:08:A0:AB:59:9A:5B:51:72:3F:DA:58:8E:81:DB:4F:A0:65:41:0E:7D:C2:65:4D:F1:A5:67:5B:47:13:52", # bitrise
                  "FF:F9:BC:4E:E9:D7:10:AF:4F:B4:C2:7C:63:85:01:A6:A2:99:09:3C:F1:56:9E:E3:60:00:31:15:91:70:EA:E9", # google-play
                ]
            ios:
              bundleId: AGG3V6QN4G.ch.procivis.one.wallet.dev
              enforceProductionBuild: false
        appVersion:
          minimum: "v1.0.0"
        eudiWalletInfo:
          providerName: "Procivis One Dev"
        featureFlags:
          trustEcosystemsEnabled: true
          refreshCredentialBatchEnabled: true
  PROCIVIS_ONE_NATIVE:
    type: PROCIVIS_ONE
    display: walletProvider.procivisOneNative
    params:
      public:
        walletName: "Procivis One iOS Dev Wallet"
        walletInstanceAttestation:
          expirationTime: 86400 # 24*60*60 seconds
          integrityCheck:
            ios:
              bundleId: AGG3V6QN4G.ch.procivis.one.wallet.ios.dev
              enforceProductionBuild: false
              trustedAttestationCAs:
                [
                  "-----BEGIN CERTIFICATE-----\nMIICITCCAaegAwIBAgIQC/O+DvHN0uD7jG5yH2IXmDAKBggqhkjOPQQDAzBSMSYw\nJAYDVQQDDB1BcHBsZSBBcHAgQXR0ZXN0YXRpb24gUm9vdCBDQTETMBEGA1UECgwK\nQXBwbGUgSW5jLjETMBEGA1UECAwKQ2FsaWZvcm5pYTAeFw0yMDAzMTgxODMyNTNa\nFw00NTAzMTUwMDAwMDBaMFIxJjAkBgNVBAMMHUFwcGxlIEFwcCBBdHRlc3RhdGlv\nbiBSb290IENBMRMwEQYDVQQKDApBcHBsZSBJbmMuMRMwEQYDVQQIDApDYWxpZm9y\nbmlhMHYwEAYHKoZIzj0CAQYFK4EEACIDYgAERTHhmLW07ATaFQIEVwTtT4dyctdh\nNbJhFs/Ii2FdCgAHGbpphY3+d8qjuDngIN3WVhQUBHAoMeQ/cLiP1sOUtgjqK9au\nYen1mMEvRq9Sk3Jm5X8U62H+xTD3FE9TgS41o0IwQDAPBgNVHRMBAf8EBTADAQH/\nMB0GA1UdDgQWBBSskRBTM72+aEH/pwyp5frq5eWKoTAOBgNVHQ8BAf8EBAMCAQYw\nCgYIKoZIzj0EAwMDaAAwZQIwQgFGnByvsiVbpTKwSga0kP0e8EeDS4+sQmTvb7vn\n53O5+FRXgeLhpJ06ysC5PrOyAjEAp5U4xDgEgllF7En3VcE3iexZZtKeYnpqtijV\noyFraWVIyd/dganmrduC1bmTBGwD\n-----END CERTIFICATE-----",
                ]
        eudiWalletInfo:
          providerName: "Procivis One iOS Dev"
          solutionId: "PROCIVIS_ONE"
          solutionVersion: "1"
          wscdType: HYBRID
        appVersion:
          minimum: "v1.0.0"
        featureFlags:
          trustEcosystemsEnabled: true
          refreshCredentialBatchEnabled: true
        walletLink: "https://docs.procivis.ch/components/wallet-app"
        walletClientId: "eudiw-abca"
        walletRegistration: OPTIONAL
        walletUnitAttestation:
          expirationTime: 2678400 # 31 days
          revocationMethod: TOKENSTATUSLIST
        deviceAuthLeeway: 60
verifierProvider:
  PROCIVIS_ONE:
    params:
      public:
        verifierName: "Procivis One Dev Verifier"
        appVersion:
          minimum: "v1.0.0"
        featureFlags:
          trustEcosystemsEnabled: true
format:
  MDOC_SHORT_EXPIRY:
    type: "MDOC"
    display:
      en: "ISO mdoc (short expiry)"
      de: "ISO mdoc (kurze Gültigkeit)"
    order: 101
    params:
      public:
        msoExpiresIn: 60
        msoExpectedUpdateIn: 60
        msoMinimumRefreshTime: 10
        leeway: 10
        revocationMethod: "MDOC_MSO_UPDATE_SUSPENSION"
transport:
  MQTT:
    type: "MQTT"
    display: "transport.mqtt"
    enabled: true
    order: 1
    params:
      private:
        brokerUrl: "mqtts://mqtt.dev.procivis-one.com:8883"
verificationProtocol:
  OPENID4VP_PROXIMITY_DRAFT00:
    display:
      en: "OpenID4VP Proximity"
      de: "OpenID4VP Nahbereich"
    order: 5
    type: "OPENID4VP_PROXIMITY_DRAFT00"
    params:
      public:
        verifier:
          interactionExpiresIn: 3600
signer:
  REGISTRATION_CERTIFICATE:
    params:
      private:
        payload:
          issuer: "https://core.dev.procivis-one"
